language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

install:
  - wget -q -O /tmp/glide.tar.gz https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
  - cd /tmp && tar -xvf glide.tar.gz && linux-amd64/glide -v
  - /tmp/linux-amd64/glide install

allow_failures:
  - go: tip

script:
  - make test

env:
  - "GO15VENDOREXPERIMENT=1"
